# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs linting - kotlin and android"
  lane :lint do
    gradle(task: "ktlintCheck")
    gradle(task: "lint")
  end

  desc "Runs all the unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Runs linting and all the unit tests"
  lane :check do
    gradle(task: "check")
  end

  desc "Runs the UI tests (requires running emulator)"
  lane :uiTest do
    gradle(task: "connectedCheck")
  end
end
