name: publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      GH_USERNAME: ${{ secrets.GH_PACKAGES_USERNAME_3DS }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_PASS_3DS }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Assemble release
      run: ./gradlew -x ryft-sample-app:assembleRelease assembleRelease

    - name: Generate source and javadoc jars
      run: ./gradlew sourcesJar javadocJar

    - name: Publish to MavenCentral
      run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
